### ISSUE TITLE
Great project. A few pointers/ideas.

### ISSUE THREAD

**Issue by jottr** [landonr/esphome-remote#4]
This is a great project @landonr.
I've been meaning to build a smart wall mounted "light switch" with Lilygo's [ESP32 Epaper display](https://www.aliexpress.com/item/1005002006058892.html). 
I think the rotary encoder could be a good interface to navigate a simplified dashboard for homeassistant.

Sadly, drawing UX on these displays is not as straightforward as I initially hoped. The [EPDiy](https://github.com/vroland/epdiy) driver is a starting point, as is the [ESPUI](https://github.com/s00500/ESPUI) library.  

I'm leaving this info here since I believe this might be interesting to others too.

**Comment by landonr** [comment]
it seems like support for the Lilygo T5-4.7 is in progress for esphome which is all we need for support https://github.com/esphome/feature-requests/issues/1109#issuecomment-986018421

however im not sure if it would work well with the rotary because it needs the display to update as fast as possible. A d-pad might work better like https://github.com/adityapattiyeri/home-remote does
